export const mobileTheme = {
  colors: {
    background: "#f8fafc",
    surface: "#ffffff",
    surfaceMuted: "#f1f5f9",
    border: "#e2e8f0",
    text: "#0f172a",
    textMuted: "#64748b",
    accent: "#6366f1",
    accentSoft: "#e0e7ff",
    success: "#10b981",
    successSoft: "#d1fae5",
    warning: "#f59e0b",
    warningSoft: "#fef3c7",
    danger: "#ef4444",
    dangerSoft: "#fee2e2",
    info: "#0ea5e9",
    infoSoft: "#e0f2fe",
    white: "#ffffff",
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 16,
    lg: 20,
    xl: 28,
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 20,
    pill: 999,
  },
  shadow: {
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
};
